### PR TITLE
Media queries added for responsive behavior

### PR DESCRIPTION
**Pull request by hmontazeri**
#13 

Media queries added

### CODE REVIEW

**Comment by hmontazeri** [comment]
image

**Comment by hmontazeri** [comment]
the widget button messes it up a little...

**Comment by bluzi** [comment]
Thanks @hmontazeri! Awesome work!
I feel like if we would get rid of the widget button and center the footer it may look much better.

Do you mind adding it to your PR?

**Comment by hmontazeri** [comment]
so you want to get rid of the whole widget or should be just hidden on mobile?

**Comment by bluzi** [comment]
I'm talking about hiding the widget only on mobile

**Comment by bluzi** [comment]
Probably using JavaScript

**Comment by hmontazeri** [comment]
CSS is enough 

image

**Comment by bluzi** [comment]
Awesome, thanks!

**Pull request merged**
