### PR TITLE
Fix #14, pass object to update

### LINKED ISSUE #14: Internal Server Error on PUT with JSON value
```
curl -X PUT -H 'Content-Type: application/json' -d '12345' https://www.jsonstore.io/1ba7860f742fc15d5b6e1508e2de1e0cde2c396f7c52a877905befb4e970eaaf/a-number
```

```
curl -X PUT -H 'Content-Type: application/json' -d 'true' https://www.jsonstore.io/1ba7860f742fc15d5b6e1508e2de1e0cde2c396f7c52a877905befb4e970eaaf/a-boolean
```

#### Both requests result in a 500:

```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>
```

### Using a JSON object work just fine:

```
curl -X PUT -H 'Content-Type: application/json' -d '{"b":true, "n":12345}' https://www.jsonstore.io/1ba7860f742fc15d5b6e1508e2de1e0cde2c396f7c52a877905befb4e970eaaf/an-object
```

```
{"result":true}
```

### PR DESCRIPTION
**Pull request by akshendra**

### CODE REVIEW

**Comment by akshendra** [comment]
Possible fix for https://github.com/bluzi/jsonstore/issues/14

**Comment by bluzi** [comment]
How do you know this method works?

**Comment by akshendra** [comment]
According to the docs here https://firebase.google.com/docs/database/web/read-and-write (Update specific fields seconds.) I have also tried the example given in readme for PUT on with my firebase config.

**Comment by bluzi** [comment]
I think it's good as is. Thanks @akshendra!

**Pull request merged**
