### PR TITLE
Simple query support 

### PR DESCRIPTION
**Pull request by akshendra**
Trying to support querying data in the json tree, using `orderByChild` and `equalTo`. Ref: https://firebase.google.com/docs/database/web/lists-of-data

> For example if we have users saved like below
```
GET /<key>/users
---
{
  "ok": true,
  "result": {
    "-LERLN9a4ZVUeNhFe_ym": {
      "age": 12,
      "name": "steph.merch"
    },
    "1": {
      "age": 11,
      "name": "john.snow"
    },
    "3": {
      "age": 1,
      "name": "karl.pilki"
    },
    "4": {
      "age": 11,
      "name": "steph.merch"
    }
  }
}
```

> We can query using parameters `key`, `value` and `number`

```
GET /<key>/users?key=age&value=11&type=number 
---
{
  "ok": true,
  "result": {
    "1": {
      "age": 11,
      "name": "john.snow"
    },
    "4": {
      "age": 11,
      "name": "steph.merch"
    }
  }
}
```

> `GET` without query parameters work as normal.

Code is a bit hacky, just wanted the idea reviewed before going any further :)

### CODE REVIEW

**Comment by bluzi** [comment]
First, I love the idea and I think it's almost essential for jsonstore to have this feature implemented, so thanks for bringing it up!

Let's talk about the interface:
Firebase clearly have lots of limitation in terms of querying data, so lets try to get the best out of it

- I think we should make it obvious to the user that the data will also be ordered by the key (unless i'm wrong), and I don't think `key` and `value` are expressive enough, as it feels like "a filter key and value" and not like "order by this key and filter by this value", if that makes any sense
- I also think we should also expose the ability to order the data without filtering it
- I'm not a fan of having to explicitly define the type of the value all the time. Do we have a way around it? maybe we can try converting it ourselves and let the user override it by supplying `type`?
- What will happen if the user will try to filter or order something that is not filterable? like an object?

**Comment by akshendra** [comment]
Thanks for reviewing.

> I think we should make it obvious to the user that the data will also be ordered by the key (unless i'm wrong), and I don't think key and value are expressive enough, as it feels like "a filter key and value" and not like "order by this key and filter by this value", if that makes any sense

You are right, the data will be ordered by the key. And I agree that the key names are not expressive enough. Naming them `orderBy` and `equalTo` might be good option.

> I also think we should also expose the ability to order the data without filtering it

If the keys are named better, this functionality is already there. Just have to remove the `equalTo`.

> I'm not a fan of having to explicitly define the type of the value all the time. Do we have a way around it? maybe we can try converting it ourselves and let the user override it by supplying type?

Definitely. Just not sure how far the type can be guessed. Probably numbers and boolean, can be easily guessed.

> What will happen if the user will try to filter or order something that is not filterable? like an object?

It will go through all the props, treating the values as children of the object, and applying the filter on them, treating everything like object. For eg,

```
GET /<key>/users
---
{
  "ok": true,
  "result": {
    "age": 12,
    "just": {
      "age": 11
    },
    "name": "steph.merch",
    "notin": {
      "age": 10
    },
    "obj": {
      "age": 11,
      "number": "10",
      "string": "string"
    }
  }
}

// applying query
GET /<key>/users?key=age&value=11&type=number
---
{
  "ok": true,
  "result": {
    "just": {
      "age": 11
    },
    "obj": {
      "age": 11,
      "number": "10",
      "string": "string"
    }
  }
}
```

**Comment by bluzi** [comment]
Cool

IMO you can rename the query parameters, improve type guessing, update the readme and let's merge

**Comment by akshendra** [comment]
Key names have been changed to `orderKey`, `filterValue` and `valueType`. Ordering data in ascending order is supported by using `orderKey` alone.

Also updated readme.

**Comment by bluzi** [comment]
Thanks @akshendra, sorry for taking the time to merge this PR, was busy lately :)

**Pull request merged**
