### PR TITLE
use env variables for config

### PR DESCRIPTION
**Pull request by akshendra**
https://github.com/bluzi/jsonstore/issues/10

Using `dotenv` to load environment from `.env` file. 
`.env.sample` included

### CODE REVIEW

**Comment by bluzi** [comment]
Hey @akshendra, sorry for taking so long to comment, had a busy week.
Anyway, I thought about it some more and I think it'll be better if we'll replace `get-link` with `get-token`, and let the client side handle the actual URL. 

What do you think?

**Comment by akshendra** [comment]
That would be better in my opinion as well. Since the client should know the URL of server, in order to fetch the link.

However, do you want to keep the .env then? I am a big fan of environment as configuration.

**Comment by bluzi** [comment]
I feel like it's unnecessary, I'd like to keep it as simple as possible to deploy an instance of jsonstore, and having to change the .env file just seems like work we can avoid by using ` window.location.hostname` :)

**Comment by akshendra** [comment]
Cool, will make another PR :)

**Pull request closed without merging**
